name: Publish Python SDK

on: workflow_dispatch

jobs:
  publish-to-pypi:
    name: Publish Python SDK
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/indexify
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: python3 -m pip install poetry --user
      - name: Build Packages
        run: python3 -m poetry build && python3 -m poetry build --directory=langchain
      - name: Publish Indexify Client to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
      - name: Publish Indexify Langchain to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: langchain/dist/
