name: Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
      branches:
      - 'main'

jobs:
  test:
    name: Test get version number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install indexify
      run: pip install . && cd langchain && pip install .
    - name: Install python dependencies
      run: cd tests && pip install -r requirements.txt
    - name: Run Tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: cd tests && ./run_tests.sh