name: Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
      branches:
      - 'main'

jobs:
  extract-version:
    name: Extract Version Number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_extraction.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install toml
        run: pip install toml
      - id: version_extraction
        run: echo "version=$(python -c 'import toml; print(toml.load(\"pyproject.toml\")[\"tool\"][\"poetry\"][\"version\"])')" >> $GITHUB_OUTPUT
  
  test-get-version:
    name: Get Version Number
    runs-on: ubuntu-latest
    needs:
      - extract-version
    steps:
      - name: Echo Extracted Version
        run: echo "Extracted Version is ${{ needs.extract-version.outputs.version }}"
        
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install indexify
      run: pip install . && cd langchain && pip install .
    - name: Install python dependencies
      run: cd tests && pip install -r requirements.txt
    - name: Run Tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: cd tests && ./run_tests.sh